name: Deploy Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "helm-chart/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-gitops-app:${{ github.sha }}

      - name: Update Helm values.yaml
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.sha }}\"/" helm-chart/values.yaml

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add helm-chart/values.yaml
          git commit -m "Update Helm chart with new image tag ${{ github.sha }}" || echo "No changes to commit"
          git push origin main

